Sem det log
OnionGrief/Chipollino pull request #250
Opened 2023-01-26 14:51 UTC by Robby-the-paladin

Добавлены логи на semdet

2023-01-26 16:14 UTC, Robby-the-paladin commented
Последний фикс про производную в размеченном regex

2023-01-27 02:11 UTC, TonitaN requested changes
На винде всё падает:
```
N = SemDet.Glushkov {b*|b|aa*} !!
```
Похоже на утечку. К сожалению, ни одного примера, где SemDet завершил бы вычисление при недетерминированном семантически автомате (например, для ab|a*) тоже запустить без падения не удалось.

Да, для логов возьмите шаблончик из рабского репозитория или из ветки логгера здесь и адаптируйте. В настоящем логгере, который у вас, немного некорректно работает перевод строки. И мы добавили в шапки типы.

2023-01-27 03:03 UTC, Robby-the-paladin commented
https://github.com/StarikTenger/Chipollino/pull/250#pullrequestreview-1272048687
Оказалось, что при попытке построить префикс по автомату использовался только первый переход из состояния. Сейчас на указанных примерах не падает.

2023-01-27 06:46 UTC, Robby-the-paladin commented
Багфикс: раньше annote не снимался после нахождения префиксов и semdet работал на аннотированном автомате.

2023-01-27 07:12 UTC, Robby-the-paladin commented
Поправлены шаблоны

2023-01-28 00:40 UTC, TonitaN commented
Всё упало:
```
N = SemDet.Thompson {a|a} !!
```

2023-01-28 01:24 UTC, TonitaN commented
Логи нужно поправить.
- вне генерируемых объектов `\\` (т.е. в ваших пояснениях) не нужны, они сбивают с толку латех и всё перестаёт собираться. Смело ставьте двойной перевод строки перед каждым новым логируемым объектом.
- и тем более вынужденные переводы строки не нужны перед `%template_`- тегами.
- поскольку сейчас в мат.режим переходим единообразно, не получится сделать красиво и без него, и внутри него. Поэтому `\\xrightarrow` заменяем на метатег `TRANSIT`, и дальше всё в рендеренном варианте будет как вам хочется

Я поправила логи, как они должны примерно выглядеть (чтобы не потерять вашу мысль, но согласовать всё с остальными):
```
	auto make_string_transition = [=](int from, alphabet_symbol through,
									  int to) {
		string f = std::to_string(from);
		string arrow = "TRANSIT{" + string(through) + "}";
		string t = std::to_string(to);
		return f + arrow + t;
	};
``` 
Без перехода в мат.режим и без его фишек. В такой версии собираются оба документа. Только ещё нужно передавать реальные имена состояний автомата, а не просто их номера, чтобы логи согласовывались друг с другом.

2023-01-28 01:26 UTC, TonitaN commented
Так что ваша задача:
- скачать самую новую версию проекта (включая последние изменения в рефале, т.к. они в том числе касаются и вашей возможности сделать логи)
- добиться того, чтобы логи были устроены так, что оба PDF собираются.

После этого опять буду смотреть.

2023-01-28 04:54 UTC, Robby-the-paladin commented
https://github.com/StarikTenger/Chipollino/pull/250#issuecomment-1407225499
У нас почему-то в автомате Томпсона переходы по эпсилону обозначаются через symbol = 'eps', а при попытке сделать to_regex эпсилон превращается в конкатенацию символов e, p, s

2024-01-07 14:56 UTC, closed without merging