Рефакторинг метода to-regex класса FiniteAutomaton #279
OnionGrief/Chipollino pull request #282
Opened 2023-10-23 08:26 UTC by AngelicHedgehog

Теперь точно добавить нечего...

2023-10-23 11:56 UTC, xendalm commented on libs/Objects/include/Objects/FiniteAutomaton.h
> +	Regex to_regex(iLogTemplate* log = nullptr) const noexcept;
Поверхностное ревью из того что сразу вижу.

Для чего тут noexcept?

2023-10-23 12:02 UTC, AngelicHedgehog commented on libs/Objects/include/Objects/FiniteAutomaton.h
> +	Regex to_regex(iLogTemplate* log = nullptr) const noexcept;
По своему предназначению: в качестве пометки для компилятора, что этот метод можно оптимизировать как не выбрасывающий исключения

2023-10-23 12:02 UTC, xendalm commented on libs/Objects/include/Objects/FiniteAutomaton.h
> +	Regex to_regex(iLogTemplate* log = nullptr) const noexcept;
Поверхностное ревью из того, что сразу вижу.

2023-10-23 12:08 UTC, xendalm commented on libs/Objects/src/FiniteAutomaton.cpp
> +		const auto& tmp_exprs = arden(tmp_tmp_exprs, i);
Во-первых, переопределение переменной, на которое жалуется пайплайн. Во-вторых нужно полностью переделать именование переменных, чтобы не было tmp и tmp_tmp и тд. Хочется, чтобы имена отражали суть, сейчас ничего не понятно.

И если не сложно, проведи тест алгоритма на рандомных регулярках. Примеры проверок уже есть в тестах, но помню, что часть из них были удалены втихую, потому что не проходили. Нужно попытаться найти (или нет) ошибки в реализации

2023-10-23 12:09 UTC, xendalm commented on libs/Objects/src/FiniteAutomaton.cpp
> +						// тут б
Старые комментарии, которые непонятно для чего и что значат тоже нужно провалидировать и исправить, если нужно

2023-10-23 12:17 UTC, mathhyyn commented on libs/Objects/src/FiniteAutomaton.cpp
> +Regex FiniteAutomaton::to_regex(iLogTemplate* log = nullptr) const noexcept {
default значение уже установлено в .h файле

2023-10-23 12:18 UTC, xendalm commented on libs/Objects/src/FiniteAutomaton.cpp
> +		const auto& tmp_exprs = arden(tmp_tmp_exprs, i);
Речь о проверке на эквивалетность языков до и после преобразования _to_fa()_.to_regex()

2023-10-23 12:32 UTC, mathhyyn commented
```
R = {(b(a|b))*}
N = Arden.Glushkov R
Equiv N R
```

![image](https://github.com/OnionGrief/Chipollino/assets/79749959/7e1fedca-7319-4363-8e47-5e0d470b130f)
все еще грустно :(

2023-10-23 17:29 UTC, AngelicHedgehog commented
Ла-дно, думал код верно выполняет свою задачу, но раз так, буду переписывать алгоритм

2023-11-23 16:42 UTC, xendalm requested changes

2023-11-23 18:13 UTC, AngelicHedgehog commented on libs/Objects/src/FiniteAutomaton.cpp
> +		return {SLAE[start_state_index][end_state_index].to_txt()};
Регулярку преобразовывал в строку, а потом обратно из-за непонимания источника ошибки, хотя и в строковом представлении результаты полностью совпадали. Возможно это действительно из-за того, что алфавит не задаётся. Попробую это исправить

Тему про тесты выношу в отдельную задачу (#...)

2023-11-23 18:37 UTC, xendalm commented on libs/Objects/src/FiniteAutomaton.cpp
> +		return {SLAE[start_state_index][end_state_index].to_txt()};
Да, очередное неочевидное условие) У нас в каждой ноде регулярки должен быть алфавит ее поддерева. При парсинге это обеспечивается тем, что мы объединяем set-ы ([пример](url)).
Можно сделать такой же механизм для методов regex_union, regex_alt, regex_star.
Если с ними возникнут проблемы, используй метод generate_alphabet (кажется сейчас он написан криво, но нужно всего лишь рекурсивно пройтись по дереву и собрать алфавит из Type::symbol). Напиши, если нужна будет помощь в его рефакторинге

2023-11-23 18:39 UTC, AngelicHedgehog commented on libs/Objects/src/FiniteAutomaton.cpp
> +		return {SLAE[start_state_index][end_state_index].to_txt()};
Ссылка на пример невалидная

2023-11-23 18:42 UTC, xendalm commented on libs/Objects/src/FiniteAutomaton.cpp
> +		return {SLAE[start_state_index][end_state_index].to_txt()};
Вижу, что все само починилось, но алфавит все же нужен. Если он сейчас не задается, конечно. Еще не успел посмотреть в дебаге

2023-11-23 18:43 UTC, xendalm commented on libs/Objects/src/FiniteAutomaton.cpp
> +	const int start_state_index = AbstractMachine::initial_state;
Это не статическое поле, если что. Просто значение по умолчанию

2023-11-23 19:09 UTC, AngelicHedgehog commented on libs/Objects/src/FiniteAutomaton.cpp
> +		return {SLAE[start_state_index][end_state_index].to_txt()};
Чекни, правильно понял, что такой вариант подойдёт?  [e1b2860](https://github.com/OnionGrief/Chipollino/pull/282/commits/e1b2860e440aa14a1a69ae22c34f375fe13a36f9)

2023-11-23 19:24 UTC, xendalm requested changes

2023-11-23 19:24 UTC, xendalm commented on libs/Objects/src/FiniteAutomaton.cpp
> +		result_regex.make_language();
make_language создает новый язык, а нужно возвращать регулярку с this->language автомата

2023-11-23 19:25 UTC, xendalm commented on libs/Objects/src/FiniteAutomaton.cpp
> +		result_regex.make_language();
```
void AlgExpression::set_language(std::shared_ptr _language) {
	language = _language;
}
```

2023-11-23 19:27 UTC, xendalm commented on libs/Objects/src/FiniteAutomaton.cpp
> +		result_regex.make_language();
А генерацию алфавита желательно все-таки переписать. Лучше через regex_union, regex_alt, regex_star
generate_alphabet сам исправлю потом, сейчас он узко-костыльный

2023-11-23 19:28 UTC, AngelicHedgehog commented on libs/Objects/src/FiniteAutomaton.cpp
> +		result_regex.make_language();
Окей, тогда буду исходить из того, что алфавит сам будет генерироваться при вызове этих методов

2023-11-23 19:30 UTC, AngelicHedgehog commented on libs/Objects/src/FiniteAutomaton.cpp
> +		result_regex.make_language();
> А генерацию алфавита желательно все-таки переписать. Лучше через regex_union, regex_alt, regex_star generate_alphabet сам исправлю потом, сейчас он узко-костыльный

В коде несколько иная сигнатура..
```
void AlgExpression::set_language(const set<Symbol>& _alphabet) {
	alphabet = _alphabet;
	language = make_shared<Language>(alphabet);
}
```

2023-11-23 19:49 UTC, xendalm commented on libs/Objects/src/FiniteAutomaton.cpp
> +		result_regex.make_language();
Нам нужно, чтобы указатели (shared_ptr) были одинаковыми, а так создастся новый через make_shared.

2023-11-23 19:51 UTC, xendalm commented on libs/Objects/src/FiniteAutomaton.cpp
> +		result_regex.make_language();
Можешь сделать copy_language метод, не принципиально) Главное чтобы логика была такая

2023-11-23 19:56 UTC, xendalm commented on libs/Objects/src/FiniteAutomaton.cpp
> +		result_regex.language = language;
Забыл, что так можно)

2023-11-23 20:03 UTC, AngelicHedgehog commented on libs/Objects/src/FiniteAutomaton.cpp
> +		result_regex.language = language;
Вообще, лучше было бы, чтоб это был отдельный меток, который может инкапсулировать прочую логику, связанную с изменением языка, однако на первое время и этого хватит

2023-11-24 23:48 UTC, xendalm requested changes

2023-11-24 23:48 UTC, xendalm commented on apps/UnitTestsApp/src/UnitTests.cpp
> +TEST(TestArden, Test_arden_on_random_regex) {
Для тестов на случайных данных у заведено отдельное приложение - MetamorphicTestsApp

2023-11-24 23:49 UTC, xendalm commented on apps/UnitTestsApp/src/UnitTests.cpp
> +TEST(TestArden, Test_arden_on_random_regex) {
Если не сложно, тест на парсинг тоже туда перенеси, пожалуйста

2023-11-25 12:01 UTC, xendalm approved these changes

2023-11-25 12:01 UTC, merged