Colorize & LogTemplate & Tester (#268, #269)
OnionGrief/Chipollino pull request #292
Opened 2023-11-08 18:38 UTC by TonitaN

- Раскраска результатов эдгаро-независимых функций (с вынесением методов раскраски в отдельный класс, чтобы не мешались в FiniteAutomaton и можно было переиспользовать в MFA)
- Исправление бага с бесконечным циклов по эпсилонам в методе parse_by_nfa
- Рефакторинг модуля Tester (по автомату и регулярке теперь работает один и тот же метод с вариантами), добавление Plot-объектов со сравнительной отрисовкой роста числа шагов разбора
- Рефакторинг логгера в варианты
- Рефакторинг toImage

Что не нравится:
- Нужно всё время вызывать метод `Colorize` в `set_parameter`. `MetaInfo` передавать напрямую нельзя: появятся циклические зависимости. Непонятно, как исправить.
- Логирование `Plot`-а далеко от идеала, впрочем, оно соответствует стилю старых логирующих функций в этом модуле. Потом нужно будет отрефакторить такие методы, разделив на логирование заголовков, основных частей и тегов.

2023-11-08 23:32 UTC, xendalm commented
Циклическую зависимость удалось починить предефайном FiniteAutomaton (если я правильно понял идею). С вашего позволения залью правки

2023-11-08 23:37 UTC, TonitaN commented
Отлично, если удалось! Тогда передавать в `set_parameter` можно будет сразу объект MetaInfo, что сэкономит буквы в реализации методов (отрефакторю всё немедленно).

P.S. - лог графиков улучшен + логгер переведён на `unordered_map`

2023-11-09 00:11 UTC, xendalm commented
> Тогда передавать в set_parameter можно будет сразу объект MetaInfo, что сэкономит буквы в реализации методов (отрефакторю всё немедленно как зальете изменения)

Не собирался отнимать у вас работу, просто сам отрефакторил по привычке

2023-11-09 00:17 UTC, TonitaN commented
О, работы у нас ещё много, следующая на очереди - интеграция кода Эдгара и метода Normalize, так что я ничуть не в обиде)

2023-11-10 18:27 UTC, mathhyyn commented
Пробую тестить графики. Так должно быть пока, что они не добавлены в шаблоны?
почему то отрендеренный шаблон съедает все, включая любой текст и переносы строк, перед графиком (и после)

step для оси Y выставляется в 0, если тест слишком простой (`Test {abab} {(ab)*} 1`)
![image](https://github.com/OnionGrief/Chipollino/assets/79749959/ba64c0e5-a153-41c0-b6f9-6198f571e524)

и не ясно что означает столбик "кол-во итераций" 
(раньше им был самый первый - кол-во раскрытий итераций Клини, т.е. числа от 0 до 12 (только сейчас поняла что мы зачем то добавляли к ним 1...), 
а сейчас кол-во шагов по автомату (я так понимаю, максимальное))
я бы переименовала, а то пришлось гадать за что столбец отвечает

2023-11-10 18:56 UTC, TonitaN commented
> Пробую тестить графики. Так должно быть пока, что они не добавлены в шаблоны? почему то отрендеренный шаблон съедает все, включая любой текст и переносы строк, перед графиком (и после)

Хаха, у меня они были только в папке `build/resources`, а не в корне. Исправлено. График с таблицей переносятся на другую страницу, но исправление этого пока в todo (расчётная высота таблицы намного больше, чем реальная, из-за эффектов adjustbox).

2023-11-10 20:31 UTC, mathhyyn requested changes
я пробежалась по finiteautomaton.cpp и не проверяла на всякие константные ссылки

2023-11-10 20:31 UTC, mathhyyn commented on libs/Objects/src/MetaInfo.cpp
> +// MetaInfo::MetaInfo() {} констуктор уже объявлен в заголовке как default
надо удалить лишние комментарии (и до этого тоже)

2023-11-10 20:31 UTC, mathhyyn commented on libs/Objects/src/MetaInfo.cpp
> +		for (auto trans : fa.states[elem].transitions) {
я видела до этого красивое [key, value] - надо принять на вооружение и как нибудь везде поисправлять.. (вместо trans.first и second)

2023-11-10 20:31 UTC, mathhyyn commented on libs/Objects/src/FiniteAutomaton.cpp
> +	MetaInfo new_meta = MetaInfo();
если я правильно поняла defaul конструктор, то его вызов `= MetaInfo()` избыточен
достаточно `MetaInfo new_meta;`

2023-11-10 20:31 UTC, mathhyyn commented on libs/Objects/src/FiniteAutomaton.cpp
> +	set<pair<int, pair<int, int>>> set_visited_eps, aux_eps;
снова куча pair.... тяжело разбираться

2023-11-10 20:31 UTC, mathhyyn commented on libs/Objects/src/FiniteAutomaton.cpp
> +	bool merged = false;
неиспользуемая переменная

2023-11-10 21:32 UTC, xendalm commented on libs/Logger/src/LogTemplate.cpp
> +unordered_map<Decoration, pair<string, bool>> decor_data = {{italic, {"\\textit", false}},
Мне кажется, такие 'константные' мапы можно объявлять глобально. Только лучше капсом

С неймингом вообще проблема в проекте, слишком мы много используем _snake_case_ из-за этого сложно читать код (различать методы, переменные и константы)
Класс MetaInfo с этим согласен))

2023-11-10 23:48 UTC, TonitaN commented on libs/Logger/src/LogTemplate.cpp
> +unordered_map<Decoration, pair<string, bool>> decor_data = {{italic, {"\\textit", false}},
Уже в h, и да, стало больше snake_case-ов.

2023-11-10 23:49 UTC, TonitaN commented on libs/Logger/src/LogTemplate.cpp
> +unordered_map<Decoration, pair<string, bool>> decor_data = {{italic, {"\\textit", false}},
Тут имеет смысл: возможно, декорации захочется расширить ещё каким-нибудь атрибутом.

2023-11-10 23:50 UTC, TonitaN commented on libs/Objects/include/Objects/iLogTemplate.h
> +		vector<pair<pair<int, long>, string>> data;
Тут тоже однозначно надо было.

2023-11-10 23:51 UTC, TonitaN commented on libs/Objects/include/Objects/FiniteAutomaton.h
> +	bool parsing_by_nfa(const string&, int&) const;
Согласна, некрасиво делать мутабельный аргумент, если он не нужен для рекурсии. Перенесен в элемент результата (и да, теперь результат возвращает Pair, но это наименьшая из возможных жертв).

2023-11-10 23:52 UTC, TonitaN commented on libs/Objects/src/FiniteAutomaton.cpp
> +	set<pair<int, pair<int, int>>> set_visited_eps, aux_eps;
Ничего лучше, чем tuple, здесь не получилось. И нет смысла вводить структуру - такой тип используется только в одной функции и нужен исключительно для отслеживания эпсилон-переходов в ней.

2023-11-10 23:53 UTC, TonitaN commented on libs/Objects/src/FiniteAutomaton.cpp
> +	set<pair<int, pair<int, int>>> set_visited_eps, aux_eps;
Да, `parsing_nfa_for` довольно сильно отрефакторился в итоге, чтобы не было смеси французского с нижегородским.

2023-11-11 08:09 UTC, mathhyyn commented on libs/Objects/src/FiniteAutomaton.cpp
> +	set<pair<int, pair<int, int>>> set_visited_eps, aux_eps;
Можно ввести структуру не внутри класса, а внутри функции

2023-11-11 08:13 UTC, TonitaN commented on libs/Objects/src/FiniteAutomaton.cpp
> +	set<pair<int, pair<int, int>>> set_visited_eps, aux_eps;
А есть ли смысл рефакторить её дальше? Функция короткая, структура чисто вспомогательная, от вложенных пар мы уже избавились, и с учётом комментариев не очень понятно, что там теперь нечитаемого.

2023-11-11 22:37 UTC, TonitaN commented
Всякие `error_refal.txt` и `err0.txt` теперь мусор: все логи ошибок рефала, во-первых, имеют имена, относящиеся к конкретным модулям, а во-вторых, расширение `raux` (вспомогательный файл для рефала). Поэтому старые txt-шки (вышеупомянутый мусор) я убрала из gitignore: их больше не должно появляться в принципе.

2023-11-11 22:46 UTC, xendalm approved these changes
Мне особо нечего добавить. Если по замечаниям @mathhyyn все разрешилось, можно сливать

2023-11-11 22:49 UTC, TonitaN commented
Подождём, может, что-нибудь ещё Аня заметит. 
А вы могли бы и пнуть за неконстантные аргументы, зря постеснялись)

2023-11-12 10:16 UTC, mathhyyn approved these changes

2023-11-12 10:43 UTC, merged