Добавлена поддержка отрицания в Thompson
OnionGrief/Chipollino pull request #297
Opened 2023-11-15 13:32 UTC by dak151449

2023-11-16 19:22 UTC, xendalm requested changes

2023-11-16 19:22 UTC, xendalm commented on libs/Objects/src/Regex.cpp
> +			State test = fa_left.first[i];
Зачем везде создается эта копия `fa_left.first[i]`? Можно же просто обращаться по индексу. Если много писать, то сделай range loop по fa_left.first. 
Везде с этим test аналогичное замечание (и переименовывать не придется:)

2023-11-16 19:22 UTC, xendalm commented on libs/Objects/src/Regex.cpp
> +			fa_states.push_back(State(fa_left.first[i].index + 1, {}, fa_left.first[i].identifier, false, transitions_state));
Во всех подобных местах лучше использовать `emplace_back`, чтобы избежать лишнего копирования. Сразу передаем аргументы конструктора

```suggestion
			fa_states.emplace_back(fa_left.first[i].index + 1,
								   set<int>(),
								   fa_left.first[i].identifier,
								   false,
								   transitions_state);
```

2023-11-18 21:06 UTC, xendalm commented
@dak151449 Посмотри пж последний коммит. Предлагаю и в других местах писать так

Забыл напомнить про тесты, но тут пока что можно только сравнить на равенство с автоматом ручной сборки. Когда глушков доедет, можно будет через него

2023-11-18 21:07 UTC, xendalm approved these changes

2023-11-18 21:24 UTC, dak151449 commented
> @dak151449 Посмотри пж последний коммит. Предлагаю и в других местах писать так
> 
> Забыл напомнить про тесты, но тут пока что можно только сравнить на равенство с автоматом ручной сборки. Когда глушков доедет, можно будет через него

https://github.com/OnionGrief/Chipollino/pull/297#discussion_r1396204618
![A8CXJ8Ek1_s](https://github.com/OnionGrief/Chipollino/assets/77326286/7c13c53c-efd0-403b-a1c8-7e2c42ef453b)

2023-11-18 21:26 UTC, xendalm commented
> [#297 (comment)](https://github.com/OnionGrief/Chipollino/pull/297#discussion_r1396204618) ![A8CXJ8Ek1_s](https://user-images.githubusercontent.com/77326286/284023835-7c13c53c-efd0-403b-a1c8-7e2c42ef453b.jpg)

Ну прости... Ну красивее же...

2023-11-19 03:12 UTC, mathhyyn commented
у нас там это.. отчетик ломается из-за `^`

2023-11-19 11:01 UTC, xendalm commented
> у нас там это.. отчетик ломается из-за `^`

Без примера сложно понять, о чем речь

2023-11-20 12:46 UTC, merged