Рефакторинг to_glushkov
OnionGrief/Chipollino pull request #298
Opened 2023-11-16 10:24 UTC by xendalm

2023-11-19 22:18 UTC, xendalm commented
Кажется, что буквальное равенство можно будет позаимствовать у обычных автоматов, только на переходах брать еще и действия с памятью в сравнение. Вынесу разделитель ';' выше, когда этим займусь. Постараюсь не слишком костылить с alphabet_symbol (Symbol)

2023-11-19 22:55 UTC, TonitaN commented
Мы считаем автоматы, у которых только переименованы ячейки памяти, равными? Или нет, для простоты?

2023-11-19 22:58 UTC, xendalm commented
> Мы считаем автоматы, у которых только переименованы ячейки памяти, равными? Или нет, для простоты?

Было бы здорово считать. Я подумаю, как лучше это сделать.

2023-11-19 22:58 UTC, xendalm commented
Чувствую, без классов эквивалентности, не обойдется

2023-11-19 23:11 UTC, TonitaN commented
Думаю, хватит нам экономить функции во фронте, и пора вводить специфические для MFA и b-regex. Например, `MemoryDependence` - поиск  зависимых ячеек памяти.

2023-11-22 13:10 UTC, dak151449 requested changes

2023-11-22 13:10 UTC, dak151449 commented on libs/Objects/src/MemoryFiniteAutomaton.cpp
>  string MemoryFiniteAutomaton::to_txt() const {
Можно обобщить с методом обычного автомата

2023-11-22 22:39 UTC, xendalm commented on libs/Objects/src/MemoryFiniteAutomaton.cpp
>  string MemoryFiniteAutomaton::to_txt() const {
Придется выносить states в базовый класс. Не хочется пока с указателями возиться. Если найдутся еще методы, которые можно будет обобщить, рассмотрю этот вариант

2023-11-23 09:33 UTC, dak151449 approved these changes

2023-11-23 09:36 UTC, merged