Марафет
OnionGrief/Chipollino pull request #299
Opened 2023-11-16 20:33 UTC by mathhyyn

+ Удаление ловушки при вызове обычных Determinize / Minimize 
close #152 
(ловушки остаются при вызове Determinize+ / Minimize+)

2023-11-17 09:57 UTC, xendalm commented
Мне все нравится, меня можно ревьюером не звать)

2023-11-19 22:16 UTC, TonitaN commented
Насчёт ^, ломающего логи. Либо придётся имплементировать рефал-стиль в logtemplate (как сделано сейчас у Ани), потому что даже простой report.tex ломается (^ допустим только в мат.режиме), либо придётся менять символ (а это тоже нелогично, поскольку обычно всё-таки используется ^).

2023-11-19 22:20 UTC, xendalm commented
Рефал стиль у Ани это replace регуляркой?? Или я чего-то не заметил

2023-11-19 22:22 UTC, TonitaN commented
Ну там-то выхода нет - ломается весь тех иначе.

2023-11-20 13:19 UTC, mathhyyn commented on libs/Objects/src/Grammar.cpp
> +	ss << "%template_grammar" << "\n\n" << "------------------------- Базисные слова -----------------------"
это надо для рефала?

2023-11-20 13:23 UTC, TonitaN commented on libs/Objects/src/Grammar.cpp
> +	ss << "%template_grammar" << "\n\n" << "------------------------- Базисные слова -----------------------"
Это надо для логгера, иначе текст до разрыва строки не будет помечен как логируемое значение комментарием (комментарий здесь один на базисные слова и на правила переписывания, а они должны быть всё-таки в разных блоках логирования). Если убрать, то не будет переноса строки. В принципе, в текст должны переводиться отдельно базисные слова и отдельно правила, то есть одним результатом to_txt не обойтись, он обязан возвращать пару. Или если хочется, чтобы `to_txt` возвращал всё-таки только строку (как везде в других местах), внутри `to_txt` придётся оставить комментарий логирования, показывающий, что это отдельные объекты.

2023-11-20 13:34 UTC, TonitaN commented
Сделано чуть хуже логирование (слова и правила смешиваются - и виной тому не рефал, а `to_txt` метод - напоминание, что нужно отрефакторить), но без `template`.

2023-11-25 00:05 UTC, xendalm requested changes

2023-11-25 00:05 UTC, xendalm commented on libs/Objects/src/FiniteAutomaton.cpp
> +		trap_dfa = dfa;
От объявления trap_dfa и лишней проверки можно избавиться. Насколько я вижу, этот автомат только для логов. Просто вызываем .remove_trap_states ниже перед логом dfa. Вернётся как раз он

2023-11-25 11:21 UTC, xendalm approved these changes

2023-11-25 11:22 UTC, merged