Новый функционал Антимирова и правки Томпсона
OnionGrief/Chipollino pull request #306
Opened 2023-11-27 14:02 UTC by dak151449

2023-11-27 14:20 UTC, xendalm requested changes

2023-11-27 14:20 UTC, xendalm commented on apps/MetamorphicTestsApp/src/MetamorphicTests.cpp
> +		ASSERT_TRUE(FiniteAutomaton::equivalent(r.to_thompson(), r.to_antimirov()));
Эта проверка не имеет смысла. Автоматы в одном языке, equivalent всегда возвращает true.
Нужно строить от разных экземпляров Regex

2023-11-27 14:20 UTC, xendalm commented on libs/Objects/include/Objects/AlgExpression.h
> +	// string to_txt() const override;
коммент не нужен

2023-11-27 14:20 UTC, xendalm commented on libs/Objects/include/Objects/BaseObject.h
> +	virtual std::string to_txt(bool eps_is_empty = true) const = 0;
Надо придумать, как не тянуть эту сигнатуру из BaseObject. Для автоматов флаг не имеет смысла, мы не хотим городить костыли

2023-11-27 14:20 UTC, xendalm commented on libs/Objects/src/FiniteAutomaton.cpp
> +	// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Кто-то котел себе о чем-то напомнить...

2023-11-27 14:20 UTC, xendalm commented on libs/Objects/src/Regex.cpp
> +											   const set<Symbol>& root_alphabet_symbol) const {
Это не символ, а сет. Опять алфавит и символ перепутан?

2023-11-27 14:20 UTC, xendalm commented on libs/Objects/src/Regex.cpp
> +	// список букв, по которым будут браться частные производные
Дай говорящее имя этому вектору. alph_regex - непонятно, о чем. В глушкове мы называли подобное symbols, например

2023-11-27 14:20 UTC, xendalm commented on libs/Objects/src/Regex.cpp
>  	set<string> check;
unordered_set

2023-11-27 14:20 UTC, xendalm commented on libs/Objects/src/Regex.cpp
> +	// спсиок {regex, производная от r, сивол по которому дифференцировали}
`vector<vector<Regex>>` не похож на `{regex, производная от r, символ по которому дифференцировали}`

2023-11-27 14:20 UTC, xendalm commented on libs/Objects/src/Regex.cpp
> +			automat_state.emplace_back(int(i), set<int>{}, state, true, transitions);
Есть конструктор с пустым label

2023-12-24 23:49 UTC, xendalm requested changes

2023-12-24 23:49 UTC, xendalm commented on libs/Objects/src/Regex.cpp
> +bool comp(Regex i, Regex j) {
Сразу скажу, что лучше лямбдой

2023-12-27 06:29 UTC, xendalm commented on apps/MetamorphicTestsApp/src/MetamorphicTests.cpp
> +   	rg.set_neg_chance(2); // для отрицания
А что эта цифра выражает? Кажется, что в этом тесте нужно проверять регулярки только с отрицанием, это возможно?

2023-12-27 06:30 UTC, dak151449 commented
Вроде всё работает верно, осталось отрефакторить (:

2023-12-27 07:01 UTC, dak151449 commented on apps/MetamorphicTestsApp/src/MetamorphicTests.cpp
> +   	rg.set_neg_chance(2); // для отрицания
Насколько часто в регулярке будет встречаться отрицание

2023-12-27 07:01 UTC, dak151449 commented on apps/MetamorphicTestsApp/src/MetamorphicTests.cpp
> +   	rg.set_neg_chance(2); // для отрицания
Этот тест и проверяет только регулярки с отрицанием

2023-12-27 08:20 UTC, xendalm commented on apps/MetamorphicTestsApp/src/MetamorphicTests.cpp
> +   	rg.set_neg_chance(2); // для отрицания
minimize не нужно вызывать, equivalent сам это сделает

2023-12-28 21:13 UTC, xendalm commented
Прежде чем запросишь ревью, вмерджи мастер внимательно, пожалуйста

2023-12-28 21:14 UTC, dak151449 commented
> Прежде чем запросишь ревью, вмерджи мастер внимательно, пожалуйста

вообще всегда так делал, но спасибо за напоминание

2023-12-30 13:04 UTC, dak151449 commented
Кто-нибудь посмотрите реализацию Regex::add_alt. Эта функция нужна, чтобы из вектора Regex собрать регулярку через альтерантивы и будет вызываться в Regex::to_aci. Сейчас в Regex::to_aci цикл с костылями, тк последняя регулярка из вектора не хотела записываться, я не смог понять в чём проблема. 

Реализация Regex::add_alt уже лежит после некоторых экспериментов, так что без критики (:

2024-01-02 14:49 UTC, xendalm commented
Можно смотреть?

2024-01-03 00:38 UTC, xendalm requested changes

2024-01-03 00:38 UTC, xendalm commented on libs/Objects/src/Regex.cpp
> +	for (size_t i = 0; i < fa_states.size(); i++) {
`Clang-Tidy: Use range-based for loop instead `

2024-01-03 00:38 UTC, xendalm commented on libs/Objects/src/Regex.cpp
> +		for (size_t j = 0; j < partial_derivatives_by_regex.size(); j++) {
`Clang-Tidy: Use range-based for loop instead `

2024-01-03 00:38 UTC, xendalm commented on libs/Objects/include/Objects/Regex.h
> +	Regex* add_alt(std::vector<Regex> res, Regex* root) const;
static 😐

2024-01-03 00:38 UTC, xendalm commented on libs/Objects/src/Regex.cpp
> +	std::sort(res.begin(), res.end(), [](Regex i, Regex j) {
`Clang-Tidy: The parameter 'i' is copied for each invocation but only used as a const reference; consider making it a const reference `

2024-01-03 00:38 UTC, xendalm commented on libs/Objects/include/Objects/AlgExpression.h
> +	AlgExpression(std::set<Symbol>); // NOLINT(runtime/explicit)
Зачем убрал explicit?

2024-01-03 00:38 UTC, xendalm commented on libs/Objects/include/Objects/AlgExpression.h
> +	AlgExpression(Type type, AlgExpression* = nullptr,
Зачем убрал explicit?

2024-01-03 00:38 UTC, xendalm commented on libs/Objects/include/Objects/BaseObject.h
> +	BaseObject(std::shared_ptr<Language>); // NOLINT(runtime/explicit)
Зачем убрал explicit?

2024-01-03 00:38 UTC, xendalm commented on libs/Objects/include/Objects/BaseObject.h
> +	BaseObject(std::set<Symbol>);		   // NOLINT(runtime/explicit)
Зачем убрал explicit?

2024-01-03 00:38 UTC, xendalm commented on libs/Objects/include/Objects/Regex.h
> +		Regex* make_copy() const override;
Лишний таб. Где ваш форматтер?

2024-01-03 00:38 UTC, xendalm commented on libs/Objects/include/Objects/FiniteAutomaton.h
> +	void set_initial_state_zero();
Комментарий не соответствует содержанию

2024-01-03 14:22 UTC, dak151449 commented on libs/Objects/src/Regex.cpp
> +	return ress.make_copy();
нейминг... в этом весь я...

2024-01-03 22:33 UTC, xendalm commented
Почти все...

![image](https://github.com/OnionGrief/Chipollino/assets/35781938/531f2f83-c935-42e6-bcc3-716ef85fbee5)


Нужно покрыть те кейсы, из-за которых разработка затянулась

2024-01-03 22:53 UTC, xendalm approved these changes

2024-01-03 22:54 UTC, merged