Методы MFA
OnionGrief/Chipollino pull request #315
Opened 2023-12-24 22:55 UTC by xendalm

Базовый IsDeterministic

- AddTrapState
- Complement
- Parse
- ParseAdditional (сопоставление с ячейками памяти за константу, cуффиксный массив + LCP + sparse table)
- ToMfaAdditional (работает, но мне не нравится :) изящно не получилось. Для каждого символа нужно знать, в каких ячейках он находится, для каких ячеек он first/last. Кроме этого нужно для каждого перехода определить, является ли он итерацией над чтением в память, без этого не получится отличить его от итерации внутри)

@TonitaN, знаю, что спросил про приоритеты и сделал все ровно наоборот... Осталось дописать прошлогодний диплом(

2023-12-25 02:10 UTC, TonitaN commented
Удалось разобраться с принимающими-не принимающими ловушками по Шмиду?

2023-12-25 17:59 UTC, xendalm commented
> Удалось разобраться с принимающими-не принимающими ловушками по Шмиду?

А на что это должно было повлиять?

2023-12-25 20:50 UTC, TonitaN commented
> > Удалось разобраться с принимающими-не принимающими ловушками по Шмиду?
> 
> А на что это должно было повлиять?

В принципе на дополнения, если есть переходы по читающим веткам. Но завтра я попробую посмотреть, насколько это актуально именно сейчас.

2023-12-28 00:58 UTC, TonitaN commented
А таки несколько быстрее экспериментальный MFA, чем обычный, построенный по рекурсивному алгоритму.

С дополнением таки потребуется дополнительная работа, в том числе из-за эпсилон-переходов (а ещё из-за пустой памяти). Их придётся устранить, причём предлагаю - простейшим методом, который строит по каждой композиции эпсилон-перехода с переходом по `t` единственный переход с меткой `t`. При этом действия над памятью умножаются: единственный нетривиальный случай умножения, если по эпсилон-переходу память закрывается, а по `t` -- открывается. Это означает, что мы можем игнорировать закрытую по эпсилон-переходу память (она сразу перезапишется) и сразу её открыть. Остальные случаи понятны: если действия одинаковы (два открытия подряд), то можно оставить одно; два закрытия подряд идти не могут; иначе переносим то действие, которое как-то меняет состояние ячейки памяти.

Очень хорошо было бы сделать генератор случайных ref-слов, чтобы добавить метаморфные тесты - через обычные юнит-тесты не очень просто отслеживать всё сразу.

2023-12-28 01:00 UTC, TonitaN commented
И пора мало-мальски добавлять MFA в интерпретатор, чтобы иметь возможность тестировать логирование. Можно максимально базово пока.

2023-12-28 17:50 UTC, dak151449 requested changes

2023-12-28 17:50 UTC, dak151449 commented on libs/Objects/include/Objects/MemoryFiniteAutomaton.h
> +struct ParingState {
хотелось бы видеть комментарии

2023-12-28 17:50 UTC, dak151449 commented on libs/Objects/include/Objects/MemoryFiniteAutomaton.h
> +	const std::string* s;
почему s, для чего s

2023-12-28 17:50 UTC, dak151449 commented on libs/Objects/include/Objects/MemoryFiniteAutomaton.h
> +	std::pair<int, bool> parse_by_mfa_additional(const std::string&) const;
что делает эта функция?

2023-12-28 17:50 UTC, dak151449 commented on libs/Objects/src/Symbol.cpp
>  	return "_eps_";
возможно имеет смысл вынести константу в заголовочный файл и тут её возвращать

2024-01-04 21:03 UTC, xendalm commented
> Их придётся устранить, причём предлагаю - простейшим методом, который строит по каждой композиции эпсилон-перехода с переходом по `t` единственный переход с меткой `t`.
@TonitaN 

В итоге все равно реализовал алгоритм с eps-замыканиями (может это и подразумевалось...) с ограничением на количество переходов по одному символу (в т.ч. eps) до 1. Для complement этого достаточно

> И пора мало-мальски добавлять MFA в интерпретатор, чтобы иметь возможность тестировать логирование. Можно максимально базово пока.

Попробуем с @mathhyyn через DSL

2024-01-05 09:13 UTC, dak151449 requested changes

2024-01-05 09:13 UTC, dak151449 commented on libs/Objects/src/FiniteAutomaton.cpp
> +		set<int> from_closure = s.top();
Тут важен порядок?

2024-01-05 09:13 UTC, dak151449 commented on libs/Objects/src/FiniteAutomaton.cpp
> +			set<int> transitions_to;
Аналогично

2024-01-05 12:46 UTC, xendalm commented on libs/Objects/src/FiniteAutomaton.cpp
> +		set<int> from_closure = s.top();
Да, для тестов)

2024-01-05 12:53 UTC, dak151449 approved these changes

2024-01-05 12:53 UTC, merged