рефакторинг функций интерпретатора и генератора
OnionGrief/Chipollino pull request #317
Opened 2024-01-18 21:48 UTC by mathhyyn

2024-01-20 23:55 UTC, xendalm requested changes

2024-01-20 23:55 UTC, xendalm commented on libs/FuncLib/include/FuncLib/Functions.h
> +Считаем дедлайном 6 часов утра 24 октября. Успехов!
```suggestion
Считаем дедлайном 6 часов утра 24 января. Успехов!
```

2024-01-20 23:55 UTC, xendalm commented on libs/Interpreter/include/Interpreter/Interpreter.h
> +using namespace FuncLib;	// NOLINT(build/namespaces)
Я бы для явности все-таки оставил обращение через ::

2024-01-21 00:44 UTC, mathhyyn commented on libs/FuncLib/include/FuncLib/Functions.h
> +Считаем дедлайном 6 часов утра 24 октября. Успехов!
Ахахах, годно!

2024-01-21 00:46 UTC, mathhyyn commented on libs/Interpreter/include/Interpreter/Interpreter.h
> +using namespace FuncLib;	// NOLINT(build/namespaces)
Можно тогда хотя бы `using FuncLib::Function` оставить?

2024-01-26 20:13 UTC, merged